# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13order_service.proto\x12\x1b\x63om.voiceorder.orderservice\"=\n\x11\x41udioOrderRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x14\n\x0c\x61udio_format\x18\x02 \x01(\t\"\xb0\x01\n\x12\x41udioOrderResponse\x12\x36\n\x08products\x18\x01 \x03(\x0b\x32$.com.voiceorder.orderservice.Product\x12\x41\n\x0eproducts_error\x18\x02 \x03(\x0b\x32).com.voiceorder.orderservice.ProductError\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\";\n\x07Product\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08sap_code\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\".\n\x0cProductError\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x32\x86\x01\n\x0cOrderService\x12v\n\x11ProcessAudioOrder\x12..com.voiceorder.orderservice.AudioOrderRequest\x1a/.com.voiceorder.orderservice.AudioOrderResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_AUDIOORDERREQUEST']._serialized_start=52
  _globals['_AUDIOORDERREQUEST']._serialized_end=113
  _globals['_AUDIOORDERRESPONSE']._serialized_start=116
  _globals['_AUDIOORDERRESPONSE']._serialized_end=292
  _globals['_PRODUCT']._serialized_start=294
  _globals['_PRODUCT']._serialized_end=353
  _globals['_PRODUCTERROR']._serialized_start=355
  _globals['_PRODUCTERROR']._serialized_end=401
  _globals['_ORDERSERVICE']._serialized_start=404
  _globals['_ORDERSERVICE']._serialized_end=538
# @@protoc_insertion_point(module_scope)
