# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voice_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13voice_service.proto\x12\x17voiceorder.orderservice\"\"\n\x0cVoiceRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\";\n\x07Product\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08sap_code\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\".\n\x0cProductError\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"\xb7\x01\n\rVoiceResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\ntranscript\x18\x03 \x01(\t\x12\x32\n\x08products\x18\x04 \x03(\x0b\x32 .voiceorder.orderservice.Product\x12=\n\x0eproducts_error\x18\x05 \x03(\x0b\x32%.voiceorder.orderservice.ProductError2o\n\x0cVoiceService\x12_\n\x0cProcessVoice\x12%.voiceorder.orderservice.VoiceRequest\x1a&.voiceorder.orderservice.VoiceResponse\"\x00\x42\x32\n\x1b\x63om.voiceorder.orderserviceB\x11VoiceServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033com.voiceorder.orderserviceB\021VoiceServiceProtoP\001'
  _globals['_VOICEREQUEST']._serialized_start=48
  _globals['_VOICEREQUEST']._serialized_end=82
  _globals['_PRODUCT']._serialized_start=84
  _globals['_PRODUCT']._serialized_end=143
  _globals['_PRODUCTERROR']._serialized_start=145
  _globals['_PRODUCTERROR']._serialized_end=191
  _globals['_VOICERESPONSE']._serialized_start=194
  _globals['_VOICERESPONSE']._serialized_end=377
  _globals['_VOICESERVICE']._serialized_start=379
  _globals['_VOICESERVICE']._serialized_end=490
# @@protoc_insertion_point(module_scope)
