# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import voice_service_pb2 as voice__service__pb2


class VoiceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessVoice = channel.unary_unary(
                '/voiceorder.orderservice.VoiceService/ProcessVoice',
                request_serializer=voice__service__pb2.VoiceRequest.SerializeToString,
                response_deserializer=voice__service__pb2.VoiceResponse.FromString,
                )


class VoiceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessVoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessVoice': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessVoice,
                    request_deserializer=voice__service__pb2.VoiceRequest.FromString,
                    response_serializer=voice__service__pb2.VoiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voiceorder.orderservice.VoiceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VoiceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessVoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/voiceorder.orderservice.VoiceService/ProcessVoice',
            voice__service__pb2.VoiceRequest.SerializeToString,
            voice__service__pb2.VoiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
